### ISSUE TITLE
June 2018 specification

### ISSUE THREAD

**Issue by crisu83** [digiaonline/graphql-php#235]
In order to update this project to conform with the [latest specification](https://facebook.github.io/graphql/June2018/#sec-String) we need to do the following (in no particular order): 

- [x] Change the order of data and error in the result (#238)
- [x] Fix ambiguity with null variable values and default values (#239)
- [x] Add support for schema extension through SDL (#240)
- [ ] Validation step for schema extension (#241)
- [x] Make SDL non-experimental (#243)
